### ISSUE TITLE
How do I use this, the instructions in the readme do not provide an example?

### ISSUE THREAD

**Issue by RyanPaulMcKenna** [UniversalRobots/Universal_Robots_ToolComm_Forwarder_URCap#11]
It says: 

"After that you should be able to use the device under ${LOCAL_DEVICE_NAME} (in our case /tmp/ttyUR) just like any local RS-485 tty device"

This forum post sheds some light on how I send and receive data from the rs485 interface: https://unix.stackexchange.com/questions/117037/how-to-send-data-to-a-serial-port-and-see-any-answer

Like so, 
write:
echo -e "\x7E\x03\xD0\xAF und normaler Text" > /dev/ttyS0
read:
cat /dev/ttyS0

But what do I send to make the gripper open or close or define a gripper width for example?
Will what I send differ depending on the gripper used (say OnRobot rg2 vs Robotiq 2FG) or is this universal?

I cannot find anything in the documentation of UR robot manuals or in my case the OnRobot RG2 manual that tells me what I should be sending here.

**Comment by fmauch** [comment]
This URCap only provides forwarding of the actual device. Usage of that device is highly depending on the actual hardware connected to the serial interface. So yes, the commands will differ significantly and are vendor-specific. So, I'm afraid, I cannot answer this here, hence I'll close this issue.
