### ISSUE TITLE
Can i make use of this urcap to send commands to my tool from a remote C# application ?

### ISSUE THREAD

**Issue by AshwathamanGovind** [UniversalRobots/Universal_Robots_ToolComm_Forwarder_URCap#5]
Hai, 
I am trying to connect and send commands to the rs485 port using this URCap file from a remote C# application. I am trying to connect but i do not see any response from the tool side. So, i doubt whether my approach is fundamentally wrong. Is this URCap file meant only for ROS?? Or can I use it with other code as well? And More importantly, As given in the readme page is this `socat socat pty,link=${LOCAL_DEVICE_NAME},raw,ignoreeof,waitslave tcp:${ROBOT_IP}:54321` command right?? 

Because there shouldn't be two socat s right? 
Sorry if i am wrong. I am new to UR development. Is there a way to verify the data i am sending to rs485 from the robot's side?

**Comment by stefanscherzinger** [comment]
Hi @AshwathamanGovind 

Sorry for not responding earlier to this issue. It got forgotten somehow. If this is still relevant for you, could you confirm that you installed the URCap according to [this installation](https://github.com/UniversalRobots/Universal_Robots_ToolComm_Forwarder_URCap/tree/add-urcap-for-convenience#installation)?
With the changes in [this PR](https://github.com/UniversalRobots/Universal_Robots_ToolComm_Forwarder_URCap/pull/6), the `rs485` URCap is directly provided within this package to make it easier to use right away and without going through the build process with Maven.

> So, i doubt whether my approach is fundamentally wrong.

No, you are perfectly right. This URCap provides the necessary level of abstraction to be used by any programming language. After setting up the connection from the remote PC (with socat) you should be able to use that `ttyUR` file in your programming language of choice for data communication over the RS485 standard.

> Because there shouldn't be two socat s right?

Yes, thanks. That was a typo. It's fixed now.

> Is there a way to verify the data i am sending to rs485 from the robot's side?

Unfortunately, I'm lacking experience here. I guess/hope there are adequate tools in Linux to test if your robot-attached device is sending something.

**Comment by stefanscherzinger** [comment]
@AshwathamanGovind

The PR changed. In case you need the `.urcap` before [Releases](https://github.com/UniversalRobots/Universal_Robots_ToolComm_Forwarder_URCap/releases) is setup, you can download it temporarily [here](https://github.com/UniversalRobots/Universal_Robots_ToolComm_Forwarder_URCap/blob/414d5f640d9977f3977ea6e32a008448d7fba8de/rs485-1.0.urcap).
